//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DE_AA_Migalkina
{
    using System;
    using System.Collections.Generic;
    
    public partial class Managers
    {
        public int ID_Manager { get; set; }
        public string Name_Manager { get; set; }
    }
}
