//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DE_AA_Migalkina
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int ID_Request { get; set; }
        public int Number_Request { get; set; }
        public System.DateTime Date_Request { get; set; }
        public string Equipment { get; set; }
        public string Type_Issue { get; set; }
        public string Description_Issue { get; set; }
        public string Name_Client { get; set; }
        public string Status { get; set; }
    }
}
