// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace CourseProject
{
    public partial class MLModel1
    {
        /// <summary>
        /// model input class for MLModel1.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"order_id")]
            public float Order_id { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"order_date")]
            public string Order_date { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"status")]
            public string Status { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"item_id")]
            public float Item_id { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"sku")]
            public string Sku { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"qty_ordered")]
            public float Qty_ordered { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"price")]
            public float Price { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"value")]
            public float Value { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"discount_amount")]
            public float Discount_amount { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"total")]
            public float Total { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"category")]
            public string Category { get; set; }

            [LoadColumn(11)]
            [ColumnName(@"payment_method")]
            public string Payment_method { get; set; }

            [LoadColumn(12)]
            [ColumnName(@"bi_st")]
            public string Bi_st { get; set; }

            [LoadColumn(13)]
            [ColumnName(@"cust_id")]
            public float Cust_id { get; set; }

            [LoadColumn(14)]
            [ColumnName(@"year")]
            public float Year { get; set; }

            [LoadColumn(15)]
            [ColumnName(@"month")]
            public string Month { get; set; }

            [LoadColumn(16)]
            [ColumnName(@"ref_num")]
            public float Ref_num { get; set; }

            [LoadColumn(17)]
            [ColumnName(@"Name Prefix")]
            public string Name_Prefix { get; set; }

            [LoadColumn(18)]
            [ColumnName(@"First Name")]
            public string First_Name { get; set; }

            [LoadColumn(19)]
            [ColumnName(@"Middle Initial")]
            public string Middle_Initial { get; set; }

            [LoadColumn(20)]
            [ColumnName(@"Last Name")]
            public string Last_Name { get; set; }

            [LoadColumn(21)]
            [ColumnName(@"Gender")]
            public string Gender { get; set; }

            [LoadColumn(22)]
            [ColumnName(@"age")]
            public float Age { get; set; }

            [LoadColumn(23)]
            [ColumnName(@"full_name")]
            public string Full_name { get; set; }

            [LoadColumn(24)]
            [ColumnName(@"E Mail")]
            public string E_Mail { get; set; }

            [LoadColumn(25)]
            [ColumnName(@"Customer Since")]
            public string Customer_Since { get; set; }

            [LoadColumn(26)]
            [ColumnName(@"SSN")]
            public string SSN { get; set; }

            [LoadColumn(27)]
            [ColumnName(@"Phone No.")]
            public string Phone_No_ { get; set; }

            [LoadColumn(28)]
            [ColumnName(@"Place Name")]
            public string Place_Name { get; set; }

            [LoadColumn(29)]
            [ColumnName(@"County")]
            public string County { get; set; }

            [LoadColumn(30)]
            [ColumnName(@"City")]
            public string City { get; set; }

            [LoadColumn(31)]
            [ColumnName(@"State")]
            public string State { get; set; }

            [LoadColumn(32)]
            [ColumnName(@"Zip")]
            public string Zip { get; set; }

            [LoadColumn(33)]
            [ColumnName(@"Region")]
            public float Region { get; set; }

            [LoadColumn(34)]
            [ColumnName(@"User Name")]
            public string User_Name { get; set; }

            [LoadColumn(35)]
            [ColumnName(@"Discount_Percent")]
            public string Discount_Percent { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel1.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"order_id")]
            public float Order_id { get; set; }

            [ColumnName(@"order_date")]
            public float[] Order_date { get; set; }

            [ColumnName(@"status")]
            public float[] Status { get; set; }

            [ColumnName(@"item_id")]
            public float Item_id { get; set; }

            [ColumnName(@"sku")]
            public float[] Sku { get; set; }

            [ColumnName(@"qty_ordered")]
            public float Qty_ordered { get; set; }

            [ColumnName(@"price")]
            public float Price { get; set; }

            [ColumnName(@"value")]
            public float Value { get; set; }

            [ColumnName(@"discount_amount")]
            public float Discount_amount { get; set; }

            [ColumnName(@"total")]
            public float Total { get; set; }

            [ColumnName(@"category")]
            public float[] Category { get; set; }

            [ColumnName(@"payment_method")]
            public float[] Payment_method { get; set; }

            [ColumnName(@"bi_st")]
            public float[] Bi_st { get; set; }

            [ColumnName(@"cust_id")]
            public float Cust_id { get; set; }

            [ColumnName(@"year")]
            public float Year { get; set; }

            [ColumnName(@"month")]
            public float[] Month { get; set; }

            [ColumnName(@"ref_num")]
            public float Ref_num { get; set; }

            [ColumnName(@"Name Prefix")]
            public float[] Name_Prefix { get; set; }

            [ColumnName(@"First Name")]
            public float[] First_Name { get; set; }

            [ColumnName(@"Middle Initial")]
            public float[] Middle_Initial { get; set; }

            [ColumnName(@"Last Name")]
            public float[] Last_Name { get; set; }

            [ColumnName(@"Gender")]
            public float[] Gender { get; set; }

            [ColumnName(@"age")]
            public float Age { get; set; }

            [ColumnName(@"full_name")]
            public float[] Full_name { get; set; }

            [ColumnName(@"E Mail")]
            public float[] E_Mail { get; set; }

            [ColumnName(@"Customer Since")]
            public float[] Customer_Since { get; set; }

            [ColumnName(@"SSN")]
            public float[] SSN { get; set; }

            [ColumnName(@"Phone No.")]
            public float[] Phone_No_ { get; set; }

            [ColumnName(@"Place Name")]
            public float[] Place_Name { get; set; }

            [ColumnName(@"County")]
            public float[] County { get; set; }

            [ColumnName(@"City")]
            public float[] City { get; set; }

            [ColumnName(@"State")]
            public float[] State { get; set; }

            [ColumnName(@"Zip")]
            public float[] Zip { get; set; }

            [ColumnName(@"Region")]
            public float Region { get; set; }

            [ColumnName(@"User Name")]
            public float[] User_Name { get; set; }

            [ColumnName(@"Discount_Percent")]
            public float[] Discount_Percent { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModel1.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

    }
}
